development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  reconnect: false
  database: ml
  username: root
  password: 

test:
  adapter: mysql2
  encoding: utf8
  host: mvp3.canhg57duqhd.ap-northeast-1.rds.amazonaws.com
  reconnect: false
  database: ml
  username: root
  password: IVmenyCUp2iPeGa

production:
  adapter: mysql2
  encoding: utf8
  host: mvp3.canhg57duqhd.ap-northeast-1.rds.amazonaws.com
  reconnect: false
  database: ml
  username: root
  password: IVmenyCUp2iPeGa

