development:
  adapter: mysql2
  encoding: utf8
  host: localhost
  reconnect: false
  database: ml
  username: root
  password: root

  # adapter: mysql2
  # encoding: utf8
  # host: influencerforce.canhg57duqhd.ap-northeast-1.rds.amazonaws.com
  # reconnect: false
  # database: ml
  # username: hive
  # password: '58363216'

test:
  adapter: mysql2
  encoding: utf8
  host: influencerforce.canhg57duqhd.ap-northeast-1.rds.amazonaws.com
  reconnect: false
  database: ml
  username: hive
  password: '58363216'

production:
  adapter: mysql2
  encoding: utf8
  host: influencerforce.canhg57duqhd.ap-northeast-1.rds.amazonaws.com
  reconnect: false
  database: ml
  username: hive
  password: '58363216'

